/* ==========================================================================
   JoãoOS XP — portfolio content (single source of truth, bilingual)
   Edit this file to update the site. Text fields are { pt, en } objects;
   plain strings are used as-is in both languages.
   Project covers live in assets/img/p/<id>.webp (generated by `npm run build:images`);
   a project without an image gets a generated pixel cover automatically.
   You can also point a project to a raw file with  img: 'assets/my-cover.png'.
   ========================================================================== */
(function () {
  'use strict';
  const JOS = (window.JOS = window.JOS || {});
  const L = (pt, en) => ({ pt, en });

  const LINKS = {
    linkedin: 'https://www.linkedin.com/in/jo%C3%A3o-anisio-marinho-da-nobrega-096358204/',
    github: 'https://github.com/caduceusj',
    itch: 'https://caduceusj.itch.io/',
    steam: 'https://store.steampowered.com/app/3964560/Malleus_Maleficarum/',
    ytmusic: 'https://music.youtube.com/browse/VLPLSwvU73KLgNjKyugBiZmka6N2yfk9-JMq',
  };

  const me = {
    name: 'João Anisio Marinho da Nobrega',
    short: 'João Anisio',
    since: 2021, // started making games ("Level" on the profile = years since)
    site: 'https://caduceusj.github.io/',
    address: { city: 'Natal', region: 'RN', country: 'Brazil' },
    emails: ['joaoanisiomn@hotmail.com', 'joaoanisiomn@gmail.com'],
    phone: '+55 84 99708-1625',
    location: L('Natal, RN — Brasil', 'Natal, RN — Brazil'),
    headline: L('Programador e Designer de Jogos', 'Game Programmer & Designer'),
    roleLine: L('Professor | Team Lead | Dev de Jogos', 'Professor | Team Lead | Game Dev'),
    languages: L('PT (Nativo) · EN (Bilíngue)', 'PT (Native) · EN (Bilingual)'),
    // rotating roles on the profile card
    roles: [
      L('Programador de Jogos', 'Game Programmer'),
      L('Game Designer', 'Game Designer'),
      L('Desenvolvedor XR / VR', 'XR / VR Developer'),
      L('Professor de Jogos Digitais', 'Digital Games Professor'),
      L('Team Lead no AKCIT', 'Team Lead at AKCIT'),
    ],
    bio: L(
      'Game designer e programador apaixonado por transformar ideias criativas em experiências divertidas e envolventes. Desenvolvo com Godot e Unity, lidero pesquisa em tecnologias imersivas (VR/MR) no AKCIT e leciono Jogos Digitais na UFRN.',
      'Game designer and programmer passionate about turning creative ideas into fun, engaging experiences. I build with Godot and Unity, lead immersive-tech (VR/MR) research at AKCIT and teach Digital Games at UFRN.'
    ),
    // "Currently" list
    now: [
      { ico: 'user_suit', org: 'UFRN', role: L('Professor Substituto de Jogos Digitais', 'Substitute Professor of Digital Games') },
      { ico: 'computer', org: 'AKCIT', role: L('Team Lead — EMBRAPII Tecnologias Imersivas', 'Team Lead — EMBRAPII Immersive Tech') },
      { ico: 'controller', org: 'Melted Peanut Studio', role: L('Programador de Jogos', 'Game Programmer') },
      { ico: 'skull', org: 'Malleus Maleficarum', role: L('Programador solo (Steam)', 'Solo Programmer (Steam)') },
    ],
    studying: [
      L('Porting (publicação multiplataforma)', 'Porting (cross-platform deployment)'),
      L('Level Design', 'Level Design'),
      L('Game Design', 'Game Design'),
      L('Scrum / Gestão de Projetos (Jira, Taiga)', 'Scrum / Project Management (Jira, Taiga)'),
    ],
    goal: L(
      'Meu objetivo é migrar de vez para a indústria de jogos, dando vida às minhas ideias criativas e construindo experiências únicas que ressoem com jogadores do mundo todo.',
      'My goal is to transition fully into the game industry, bringing my creative ideas to life and building unique experiences that resonate with players worldwide.'
    ),
    linkedinSummary: L(
      'Olá! Sou Game Designer e Programador de Jogos, apaixonado por transformar ideias criativas em experiências divertidas e envolventes. Trabalho principalmente com Godot e Unity. Tenho experiência com Realidade Virtual e Projeção Mapeada usando CAVE Systems em Unity. Líder da equipe AKCIT focada em aplicações de VR/MR para Arte e Música.',
      'Hello! I am a Game Designer and Game Programmer passionate about turning creative ideas into fun and engaging experiences. I work mainly with Godot and Unity. I have experience with Virtual Reality and Projection Mapping using CAVE systems in Unity. Leader of the AKCIT team focused on VR/MR applications for Art and Music.'
    ),
    linkedinHeadline: L(
      'Professor de Jogos Digitais | Team Lead - AKCIT | Desenvolvedor Godot & Unity',
      'Digital Games Professor | Team Lead - AKCIT | Godot & Unity Developer'
    ),
    keySkills: 'VR · AR · Mixed Reality · Godot · Unity · C# · Scrum',
    links: LINKS,
  };

  // ------------------------------------------------------------------ projects
  // kind: game | serious | xr | music      eng: engines used
  const projects = [
    { id: 'malleusgame', title: 'Malleus Maleficarum', eng: ['Godot'], kind: 'game', featured: true,
      desc: L('Que comece a caça às bruxas!', 'Let the Witch Hunt Begin!'),
      url: 'https://caduceusj.itch.io/malleus-maleficarum', steam: LINKS.steam,
      role: L('Programador solo', 'Solo Programmer'), award: L('Vencedor da Hallowjam 2023', 'Hallowjam 2023 Winner'),
      tags: ['Metroidvania', '2D', 'Dark Fantasy'] },
    { id: 'almas', title: 'As Almas da Floresta', eng: ['Godot'], kind: 'game', featured: true,
      desc: L('Explore a floresta e colete feitiços mágicos!', 'Explore the forest and collect magical spells!'),
      url: 'https://caduceusj.itch.io/as-almas-da-floresta',
      role: L('Programador de gameplay — Melted Peanut Studio', 'Gameplay Programmer — Melted Peanut Studio'), tags: [L('Exploração', 'Exploration')] },
    { id: 'baroneza', title: 'Baroneza', eng: ['Godot'], kind: 'game', featured: true,
      desc: L('Primeiro grande projeto. Finalista da Game Jam Plus.', 'First major project. Game Jam Plus Finalist.'),
      url: 'https://caduceusj.itch.io/baroneza', award: L('Finalista da Game Jam Plus 2022/2023', 'Game Jam Plus 2022/2023 Finalist'), tags: ['Game Jam'] },
    { id: 'gargantua', title: 'Gargantua', eng: ['Unity'], kind: 'game',
      desc: L('Consegue ouvir ele te chamando?', 'Can you hear him calling you?'), url: 'https://caduceusj.itch.io/gargantua' },
    { id: 'dodgeboy', title: 'Dodge Boy', eng: ['Godot'], kind: 'game',
      desc: L('Conquiste a sua liberdade!', 'Earn your freedom!'), url: 'https://caduceusj.itch.io/dodge-boy' },
    { id: 'fofoca', title: 'Fofoca', eng: ['Godot'], kind: 'game',
      desc: L('Espalhe fofocas usando o melhor das suas habilidades.', 'Gossip around using the best of your abilities.'), url: 'https://caduceusj.itch.io/fofoca' },
    { id: 'elph', title: 'E.L.P.H', eng: ['Godot'], kind: 'game',
      desc: L('Mecânicas únicas, incluindo sistemas de elevadores.', 'Unique game mechanics including elevator systems.'), url: 'https://caduceusj.itch.io/elph' },
    { id: 'bastille', title: 'Breaking Bastille', eng: ['Unity'], kind: 'game',
      desc: L('Uma história de Justiça.', 'A story of Justice.'), url: 'https://caduceusj.itch.io/breaking-bastille' },
    { id: 'cropfi', title: 'Crop-fi', eng: ['Godot'], kind: 'game',
      desc: L('Um jogo relaxante sobre jardinagem.', 'A chill game about gardening.'), url: 'https://deadpix.itch.io/crop-fi', tags: ['Chill'] },
    { id: 'jamsession', title: 'Jam Session', eng: ['Godot'], kind: 'game',
      desc: L('Entre na Zona neste jogo de ritmo.', 'Enter the Zone in this Rhythm Game.'), url: 'https://caduceusj.itch.io/jam-session', tags: [L('Ritmo', 'Rhythm')] },
    { id: 'awa', title: 'AWA', eng: ['Godot'], kind: 'game',
      desc: L('Químicas Malucas — point & click de reações químicas.', 'Crazy Chemistries — chemical reaction point & click.'), url: 'https://caduceusj.itch.io/awa', tags: ['Point & Click'] },
    { id: 'tacalafoga', title: 'Taca-La-Foga', eng: ['Godot'], kind: 'game',
      desc: L('Agiotagem Flamejante.', 'Flaming Loan Sharking.'), url: 'https://caduceusj.itch.io/taca-la-foga' },
    { id: 'trendmancer', title: 'Trendmancer', eng: ['Godot'], kind: 'game',
      desc: L('Jogo de simulação.', 'Simulation game.'), url: 'https://caduceusj.itch.io/trendmancer', tags: [L('Simulação', 'Simulation')] },
    { id: 'dinamina', title: 'Dinamina', eng: ['Godot'], kind: 'game',
      desc: L('DNA DE DINOSSAURO.', 'DINOSAUR DNA.'), url: 'https://caduceusj.itch.io/dinamina' },
    { id: 'catcha', title: 'Catcha', eng: ['Godot'], kind: 'game',
      desc: L('Sinta a emoção! Porque estabilidade financeira é superestimada.', 'Feel the thrill! Because financial stability is overrated.'), url: 'https://caduceusj.itch.io/catcha' },
    { id: 'conserto', title: 'Conserto AR-riscado', eng: ['Godot'], kind: 'game',
      desc: L('Ventile seus amigos nesse calor.', 'Fan your friends in this heat.'), url: 'https://caduceusj.itch.io/conserto-ar-riscado' },
    { id: 'quentura', title: 'Quentura', eng: ['Godot'], kind: 'game',
      desc: 'Ventile seus amigos nesse calor da bexiga.', url: 'https://caduceusj.itch.io/quentura' },
    { id: 'nolegs', title: 'I Have No Legs But I Must Sit', eng: ['Unity'], kind: 'game',
      desc: L('Entre nas Chairrooms — ambientes procedurais.', 'Enter the Chairrooms — procedural environments.'), url: 'https://caduceusj.itch.io/i-have-no-legs', tags: [L('Procedural', 'Procedural')] },
    { id: 'choose', title: 'Choose', eng: ['Godot'], kind: 'game',
      desc: L('Qual lado você escolhe?', 'Which side do you choose?'), url: 'https://caduceusj.itch.io/choose' },
    { id: 'supervisor', title: 'The Supervisor', eng: ['Unity'], kind: 'game',
      desc: L('Seu tempo é limitado para conduzir os testes. Boa sorte!', 'Your time is limited to conduct the tests. Good luck!'), url: 'https://bizarre-programming.itch.io/the-supervisor' },
    { id: '4tardes', title: '4 Tardes no GameLab', eng: ['Godot'], kind: 'game',
      desc: L('Sobreviva com o controle do ar condicionado.', 'Survive with the air conditioner remote.'), url: 'https://caduceusj.itch.io/4-tardes-no-gamelab' },
    { id: 'germinarium', title: 'Germinarium', eng: ['Godot'], kind: 'game',
      desc: L('Floresça uma nova esperança.', 'Bloom a new hope.'), url: 'https://caduceusj.itch.io/germinarium' },
    { id: 'homesick', title: 'Home Sick', eng: ['Godot'], kind: 'game',
      desc: L('Jogo desenvolvido em 48h para a PONG game jam.', 'Game made in 48 hours for the PONG game jam.'), url: 'https://caduceusj.itch.io/home-sick', tags: ['Game Jam', '48h'] },
    { id: 'picc', title: 'PICC Line Training', eng: ['Unity', 'Godot'], kind: 'serious', featured: true,
      desc: L('Simulação de treinamento médico para cateter PICC em neonatos.', 'Medical training simulation for PICC line in neonates.'), url: null,
      role: L('Desenvolvedor de Serious Games — UFRN', 'Serious Games Developer — UFRN'), tags: ['Serious Game', L('Saúde', 'Healthcare')] },
    { id: 'separatio', title: 'Separatio', eng: ['Godot'], kind: 'xr', featured: true,
      desc: L('Um projeto de VR sobre Isolamento.', 'A VR project about Isolation.'), url: null, tags: ['VR'] },
    { id: 'handtracking', title: 'Hand Tracking', eng: ['Unity'], kind: 'xr',
      desc: L('Contagem de dedos com Unity e Ultraleap.', 'Finger Counting with Unity and Ultraleap.'), url: null,
      role: L('Desenvolvedor de Serious Games — UFRN', 'Serious Games Developer — UFRN'), tags: ['Ultraleap', 'Hand Tracking'] },
    { id: 'songs', title: 'My Songs', eng: ['BeepBox'], kind: 'music',
      desc: L('Músicas que faço por diversão!', 'Songs I make for fun!'), url: LINKS.ytmusic },
  ];

  // Long description of the featured game (Malleus window)
  const malleus = {
    id: 'malleusgame',
    meta: L('Engine: Godot 4.4 | Função: Programador solo | Agora na Steam!', 'Engine: Godot 4.4 | Role: Solo Programmer | Now on Steam!'),
    text: L(
      'Um metroidvania sombrio, nascido das brasas de uma game jam de 2023 (vencedor da Hallowjam) e agora reconstruído com muito mais ambição. Como programador solo, canalizei mais de 3 anos de conhecimento em mecânicas intrincadas, inimigos variados e uma jogabilidade fluida, com uma identidade visual única.',
      'A dark metroidvania, born from the embers of a 2023 game jam (Hallowjam Winner), now rebuilt with greater ambition. As the Solo Programmer, channeling 3+ years of knowledge into intricate mechanics, diverse foes, and smooth gameplay with a unique visual identity.'
    ),
    tags: ['Godot 4.4', 'Metroidvania', L('Programador solo', 'Solo Programmer'), '2D Platformer', 'Dark Fantasy', L('Lançamento na Steam', 'Steam Release')],
    team: 'Marcos Arthur, Luis Eduardo Sales, Gabriel Henrique Bessa, Guilherme Santos Rosas',
  };

  // ------------------------------------------------------------------ skills
  // cat: dev | design | xr | prod      tile: { brand | glyph | text, color }
  const skills = [
    { id: 'godot', name: 'Godot Engine', cat: 'dev', tile: { brand: 'godot', color: '#478cbf' }, level: L('Programador de Jogos', 'Game Programmer'), eng: 'Godot',
      note: L('Engine principal: Malleus Maleficarum (Steam), As Almas da Floresta e dezenas de jogos de game jam. Tutorial na IEEE VR 2026 sobre prototipagem VR com Godot e XR Tools.', 'Main engine: Malleus Maleficarum (Steam), As Almas da Floresta and dozens of game-jam games. Tutorial at IEEE VR 2026 on VR prototyping with Godot and XR Tools.') },
    { id: 'unity', name: 'Unity', cat: 'dev', tile: { brand: 'unity', color: '#2f3744' }, level: L('Programador de Jogos', 'Game Programmer'), eng: 'Unity',
      note: L('Instalação CAVE de 4 paredes em HDRP, pesquisa em VR/MR no AKCIT e serious games na UFRN.', '4-wall CAVE installation in HDRP, VR/MR research at AKCIT and serious games at UFRN.') },
    { id: 'gdscript', name: 'GDScript', cat: 'dev', tile: { text: 'GD', color: '#3c6a94' }, level: L('Scripting no Godot', 'Godot Scripting'), eng: 'Godot' },
    { id: 'csharp', name: 'C#', cat: 'dev', tile: { text: 'C#', color: '#7a3a95' }, level: L('Programador C#', 'C# Programmer'), eng: 'Unity' },
    { id: 'cpp', name: 'C++', cat: 'dev', tile: { brand: 'cpp', color: '#00599c' }, level: L('Programador C++', 'C++ Programmer') },
    { id: 'python', name: 'Python', cat: 'dev', tile: { brand: 'python', color: '#306998' }, level: L('Programador Python', 'Python Programmer') },
    { id: 'web', name: 'HTML/CSS/JS', cat: 'dev', tile: { brand: 'html5', color: '#e34f26' }, level: L('Desenvolvimento Web', 'Web Development'),
      note: L('Este portfólio inteiro: HTML, CSS e JavaScript puros, sem frameworks.', 'This whole portfolio: plain HTML, CSS and JavaScript, no frameworks.') },
    { id: 'porting', name: 'Porting', cat: 'dev', tile: { glyph: 'switch', color: '#1f9db0' }, level: L('Multiplataforma', 'Cross-Platform'), studying: true },
    { id: 'ai', name: L('Programação de IA', 'AI Programming'), cat: 'dev', tile: { glyph: 'robot', color: '#d4572a' }, level: L('IA de Jogos', 'Game AI') },
    { id: 'gamedesign', name: 'Game Design', cat: 'design', tile: { glyph: 'lightbulb', color: '#d9822b' }, level: L('Designer', 'Designer'), studying: true,
      note: L('Game jams como designer e programador; vencedor da Hallowjam 2023.', 'Game jams as designer and programmer; Hallowjam 2023 winner.') },
    { id: 'leveldesign', name: 'Level Design', cat: 'design', tile: { glyph: 'map', color: '#2e9b5a' }, level: L('Level Designer', 'Level Designer'), studying: true },
    { id: 'uiux', name: 'UI/UX Design', cat: 'design', tile: { glyph: 'layout', color: '#b04fc0' }, level: L('Designer UI/UX', 'UI/UX Designer') },
    { id: 'xr', name: 'VR/AR/MR', cat: 'xr', tile: { brand: 'oculus', color: '#5b3fd0' }, level: L('Tecnologias Imersivas', 'Immersive Tech'),
      note: L('Team Lead no AKCIT (VR/MR para Arte e Música) e 4 contribuições na IEEE VR 2026.', 'Team Lead at AKCIT (VR/MR for Art & Music) and 4 contributions at IEEE VR 2026.') },
    { id: 'projection', name: L('Projeção Mapeada', 'Projection Mapping'), cat: 'xr', tile: { glyph: 'projector', color: '#1788a8' }, level: L('Sistemas CAVE', 'CAVE Systems'),
      note: L('"Draught, Fish, and Presence": instalação CAVE de 4 paredes com Unity HDRP.', '"Draught, Fish, and Presence": 4-wall CAVE installation with Unity HDRP.') },
    { id: 'scrum', name: 'Scrum / Jira', cat: 'prod', tile: { brand: 'jira', color: '#0a56cf' }, level: L('Gestão de Projetos', 'Project Management'), studying: true,
      note: L('Scrum com Taiga/Jira liderando a equipe do AKCIT.', 'Scrum with Taiga/Jira leading the AKCIT team.') },
    { id: 'adobe', name: L('Suíte Adobe', 'Adobe Suite'), cat: 'prod', tile: { glyph: 'brush', color: '#c4281c' }, level: L('Ferramentas Criativas', 'Creative Tools') },
    { id: 'git', name: 'Git & GitHub', cat: 'prod', tile: { brand: 'git', color: '#d6402a' }, level: L('Controle de Versão', 'Version Control') },
  ];

  // ------------------------------------------------------------------ experience
  // kind: teach | research | games | it       current: true => "Present"
  const jobs = [
    { id: 'ufrn-prof', kind: 'teach', ico: 'user_suit', current: true,
      title: L('Professor Substituto — Jogos Digitais', 'Substitute Professor — Digital Games'),
      org: 'UFRN | Natal, Brasil', period: L('Ago 2025 – Presente', 'Aug 2025 – Present'),
      text: L('Ministrando disciplinas de Jogos Digitais na Universidade Federal do Rio Grande do Norte.', 'Teaching Digital Games courses at the Federal University of Rio Grande do Norte.') },
    { id: 'akcit', kind: 'research', ico: 'computer', current: true,
      title: L('Team Lead P&D — AKCIT', 'Team Lead R&D — AKCIT'),
      org: 'Centro de Competência EMBRAPII em Tecnologias Imersivas | Natal', period: L('Mai 2025 – Presente', 'May 2025 – Present'),
      text: L('Liderança da equipe AKCIT focada em aplicações de VR/MR para Arte e Música. Gestão de uma grande equipe para entregar experiências imersivas de ponta. Projeção mapeada e desenvolvimento em Unity. Escrita de artigos científicos. Uso de Taiga/Jira com Scrum.',
        'Leading the AKCIT team focused on VR/MR applications for Art & Music. Managing a large team to deliver cutting-edge immersive experiences. Projection Mapping and Unity development. Scientific paper writing. Using Taiga/Jira with Scrum.') },
    { id: 'melted', kind: 'games', ico: 'controller', current: true,
      title: L('Programador de Jogos', 'Game Programmer'),
      org: 'Melted Peanut Studio | Natal, Brasil', period: L('Jan 2024 – Presente', 'Jan 2024 – Present'),
      text: L('Programador de gameplay de "As Almas da Floresta" com Godot Engine.', 'Gameplay Programmer for "Almas da Floresta" with Godot Engine.') },
    { id: 'gamelab', kind: 'teach', ico: 'monitor',
      title: L('Monitor do Game Lab', 'Game Lab Monitor'),
      org: 'Metrópole Digital — IMD/UFRN | Natal', period: L('Nov 2023 – Mai 2025', 'Nov 2023 – May 2025'),
      text: L('Supervisão do laboratório de jogos, apoio aos alunos, manutenção de equipamentos e resolução de problemas técnicos.', 'Supervised the game lab, assisted students, maintained equipment, troubleshot technical problems.') },
    { id: 'serious', kind: 'research', ico: 'bug',
      title: L('Desenvolvedor de Serious Games', 'Serious Games Developer'),
      org: 'UFRN | Natal, Brasil', period: L('Out 2023 – Mai 2025', 'Oct 2023 – May 2025'),
      text: L('Simulação de treinamento de cateter PICC para neonatos e projeto de contagem de dedos com Hand Tracking.', 'PICC line training simulation for neonates and Hand Tracking Finger Counting project.') },
    { id: 'semurb', kind: 'it', ico: 'printer',
      title: L('Assistente Técnico de TI', 'IT Technical Assistant'),
      org: 'SEMURB | Natal, Brasil', period: L('Set 2022 – Nov 2023', 'Sep 2022 – Nov 2023'),
      text: L('Configuração de impressoras, formatação de arquivos eletrônicos e suporte à manutenção de software.', 'Printer configuration, electronic file formatting, software maintenance support.') },
    { id: 'btn', kind: 'it', ico: 'server',
      title: L('Técnico de Suporte de TI', 'IT Support Technician'),
      org: 'BTN Soluções | Natal, Brasil', period: L('Mar 2022 – Jun 2022', 'Mar 2022 – Jun 2022'),
      text: L('Implantação de redes, suporte a usuários, manutenção de PCs e servidores. Ampliação de conhecimentos de software e de organização.', 'Network deployment, user support, PC & server troubleshooting. Gained broad software and organizational knowledge.') },
    { id: 'forlove', kind: 'games', ico: 'joystick', current: true,
      title: L('Game Developer For Love', 'Game Developer For Love'),
      org: 'Natal, Brasil', period: L('2021 – Presente', '2021 – Present'),
      text: L('Diversas game jams como programador líder ou designer. Mais de 23 projetos no Itch.io. Programador solo em Malleus Maleficarum (Steam).', 'Numerous game jams as lead programmer or designer. 23+ projects on Itch.io. Solo programmer on Malleus Maleficarum (Steam).') },
  ];

  // ------------------------------------------------------------------ education / research / awards
  const education = [
    { id: 'msc', ico: 'award_star_gold_1', title: L('Mestrado — Desenvolvimento de Produtos e Processos', "Master's — Product & Process Development"), org: 'UFRN', period: L('Mar 2025 – Jun 2027', 'Mar 2025 – Jun 2027'), current: true },
    { id: 'bti', ico: 'book_open', title: L('Bacharelado em Tecnologia da Informação', 'Bachelor of Information Technology'), org: 'UFRN', period: '2020 – 2024' },
    { id: 'games', ico: 'controller', title: L('Estudos Especializados em Jogos Digitais', 'Specialized Studies in Digital Games'), org: 'Metrópole Digital — IMD/UFRN', period: L('Mai 2022 – Dez 2024', 'May 2022 – Dec 2024') },
    { id: 'mba', ico: 'user_suit', title: L('Fast MBA: Liderança e Gestão de Pessoas', 'Fast MBA: Leadership & People Management'), org: 'Fast MBA', period: L('Fev 2025 – Mar 2025', 'Feb 2025 – Mar 2025') },
    { id: 'sebrae', ico: 'vcard', title: L('Certificado em Atendimento ao Cliente', 'Customer Service Certificate'), org: 'SEBRAE', period: L('Mar 2022', 'Mar 2022') },
  ];

  const research = [
    { type: L('Artigo', 'Paper'), key: 'paper', venue: 'IEEE VR 2026',
      title: 'Eliciting Care in VR: A Multi-Modal Pseudo-Haptic Approach to Virtual Object Fragility',
      by: 'Nobrega, Freitas, Melo, Lucena, Souza', note: L('Estudo com N=31', 'N=31 study') },
    { type: 'Demo', key: 'demo', venue: 'IEEE VR 2026',
      title: 'Hands-on Fragility: A Multi-Modal Pseudo-Haptic System for Delicate Interaction in VR',
      by: 'AKCIT-IMD/UFRN' },
    { type: L('Artigo completo', 'Full Paper'), key: 'full', venue: 'IEEE VR 2026',
      title: 'Draught, Fish, and Presence: Teaching Semi-Arid Ecology with a CAVE',
      note: L('Instalação CAVE de 4 paredes, Unity HDRP (survey N=38)', '4-wall CAVE installation, Unity HDRP (N=38 survey)') },
    { type: 'Tutorial', key: 'tutorial', venue: 'IEEE VR 2026',
      title: 'Rapid VR Prototyping for Academia and Industry: Building Interactive Experiences with Godot and XR Tools',
      note: L('Tutorial de 3 horas', '3-hour tutorial') },
  ];

  // kind: gold | silver | bronze | star | lock       ico: sprite icon
  const achievements = [
    { id: 'hallowjam', ico: 'award_star_gold_1', kind: 'gold', year: '2023', open: { app: 'project', key: 'malleusgame' },
      title: L('Vencedor — Hallowjam 2023', 'Winner — Hallowjam 2023'),
      text: L('Malleus Maleficarum venceu a Hallowjam 2023.', 'Malleus Maleficarum took first place at Hallowjam 2023.') },
    { id: 'steam', ico: 'controller', kind: 'gold', open: { app: 'malleus' },
      title: L('Lançamento na Steam', 'Released on Steam'),
      text: L('Malleus Maleficarum, programado solo em Godot 4.4, chegou à Steam.', 'Malleus Maleficarum, solo-programmed in Godot 4.4, is out on Steam.') },
    { id: 'ieee-paper', ico: 'medal_gold_1', kind: 'gold', year: '2026', open: { app: 'education' },
      title: L('IEEE VR 2026 — Artigo', 'IEEE VR 2026 — Paper'),
      text: L('Eliciting Care in VR: abordagem pseudo-háptica multimodal.', 'Eliciting Care in VR: a multi-modal pseudo-haptic approach.') },
    { id: 'ieee-full', ico: 'medal_gold_1', kind: 'gold', year: '2026', open: { app: 'education' },
      title: L('IEEE VR 2026 — Artigo completo', 'IEEE VR 2026 — Full Paper'),
      text: L('Draught, Fish, and Presence: ecologia do semiárido em um CAVE.', 'Draught, Fish, and Presence: semi-arid ecology in a CAVE.') },
    { id: 'ieee-demo', ico: 'medal_gold_2', kind: 'silver', year: '2026', open: { app: 'education' },
      title: L('IEEE VR 2026 — Demo', 'IEEE VR 2026 — Demo'),
      text: L('Hands-on Fragility: interação delicada em VR.', 'Hands-on Fragility: delicate interaction in VR.') },
    { id: 'ieee-tut', ico: 'medal_gold_2', kind: 'silver', year: '2026', open: { app: 'education' },
      title: L('IEEE VR 2026 — Tutorial', 'IEEE VR 2026 — Tutorial'),
      text: L('Tutorial de 3 horas: prototipagem rápida de VR com Godot e XR Tools.', '3-hour tutorial: rapid VR prototyping with Godot and XR Tools.') },
    { id: 'gjplus', ico: 'medal_gold_3', kind: 'silver', year: '2022/2023', open: { app: 'project', key: 'baroneza' },
      title: L('Finalista — Game Jam Plus', 'Finalist — Game Jam Plus'),
      text: L('Baroneza chegou à final da Game Jam Plus.', 'Baroneza reached the Game Jam Plus finals.') },
    { id: 'lead', ico: 'computer', kind: 'star', year: '2025', open: { app: 'experience' },
      title: L('Team Lead — AKCIT', 'Team Lead — AKCIT'),
      text: L('Liderança de equipe de P&D em tecnologias imersivas.', 'Leading an immersive-tech R&D team.') },
    { id: 'prof', ico: 'user_suit', kind: 'star', year: '2025', open: { app: 'experience' },
      title: L('Professor — UFRN', 'Professor — UFRN'),
      text: L('Professor Substituto de Jogos Digitais.', 'Substitute Professor of Digital Games.') },
    { id: 'itch', ico: 'joystick', kind: 'star', open: { app: 'projects' },
      title: L('Prolífico', 'Prolific'),
      text: L('Mais de 23 projetos publicados no Itch.io.', '23+ projects published on Itch.io.') },
    { id: 'sbgames', ico: 'rosette', kind: 'bronze', year: '2025',
      title: L('SBGames / SIBGRAPI / SVR 2025', 'SBGames / SIBGRAPI / SVR 2025'),
      text: L('Participação em conferências.', 'Conference participation.') },
    { id: 'org', ico: 'flag_green', kind: 'bronze', year: '2024',
      title: L('Organizador — GameLab Jam 2024.2', 'Organizer — GameLab Jam 2024.2'),
      text: L('Organização da game jam do GameLab.', 'Organized the GameLab game jam.') },
    { id: 'gjip', ico: 'flag_blue', kind: 'bronze', year: '2023',
      title: L('Participante — Game Jam IP Challenge', 'Participant — Game Jam IP Challenge'),
      text: L('Game Jam IP Challenge 2023.', 'Game Jam IP Challenge 2023.') },
    { id: 'gjplus22', ico: 'flag_yellow', kind: 'bronze', year: '2022',
      title: L('Participante — Game Jam+', 'Participant — Game Jam+'),
      text: L('Game Jam+ 2022.', 'Game Jam+ 2022.') },
    { id: 'next', ico: 'lock', kind: 'lock', open: { app: 'contact' },
      title: L('Próxima missão: indústria de jogos em tempo integral', 'Next quest: full-time in the games industry'),
      text: L('Bloqueada — ajude a destravar! Vamos conversar.', 'Locked — help unlock it! Let’s talk.') },
  ];

  JOS.data = { me, links: LINKS, projects, malleus, skills, jobs, education, research, achievements };

  // convenience lookups
  JOS.project = (id) => projects.find((p) => p.id === id);
  JOS.engineLabel = (p) => p.eng.join(' + ');
})();
