/* JoãoOS XP — UI strings (pt / en). Portfolio content lives in data.js. */
(function () {
  'use strict';
  const JOS = (window.JOS = window.JOS || {});
  JOS.strings = {
    en: {
      'meta.title': 'João Anisio — Game Programmer & Designer · Portfolio',
      'meta.desc': 'Portfolio of João Anisio Marinho da Nobrega — game programmer & designer (Godot, Unity), professor of Digital Games at UFRN and XR team lead at AKCIT. Creator of Malleus Maleficarum on Steam.',
      close: 'Close', start: 'start',
      'boot.skip': 'click to skip', 'login.begin': 'To begin, click your user name', 'login.sub': 'Game Programmer & Designer', 'login.off': 'After you log on, explore the desktop',
      'tray.lang': 'Language: click to switch (PT / EN)', 'tray.sound': 'UI sounds', 'tray.desktop': 'Show desktop',
      'sm.all': 'All Programs', 'sm.programs': 'Programs', 'sm.places': 'Places and links', 'sm.back': 'Back', 'sm.logoff': 'Log Off', 'sm.turnoff': 'Turn Off',
      'ctx.open': 'Open', 'ctx.refresh': 'Refresh', 'ctx.display': 'Display Properties', 'ctx.projects': 'My Projects', 'ctx.terminal': 'Terminal', 'ctx.about': 'About JoãoOS XP',
      'wm.min': 'Minimize', 'wm.max': 'Maximize', 'wm.restore': 'Restore', 'wm.close': 'Close',
      'bal.malleus.t': 'Malleus Maleficarum is out on Steam!', 'bal.malleus.x': 'My solo-programmed metroidvania is live. Come take a look.', 'bal.malleus.a': 'See the game',
      'bal.contact.t': 'Liked what you saw?', 'bal.contact.x': 'Let’s talk about games, research or a collaboration.', 'bal.contact.a': 'Say hello',
      'egg.t': 'Cheat activated!', 'egg.x': '+30 lives. You found the Konami code.',
      'sd.title': 'Thanks for visiting!', 'sd.text': 'JoãoOS XP is now safe to leave. Have a great day — and let’s build something together.', 'sd.restart': 'Restart', 'sd.contact': 'Say hello',

      'wel.sub': 'Profile & highlights', 'wel.explore': 'Explore', 'wel.now': 'Currently',
      'sheet.class': 'Class', 'sheet.level': 'Level', 'sheet.xp': 'XP to next level: {n}%', 'sheet.guild': 'Guild', 'sheet.weapons': 'Weapons', 'sheet.spawn': 'Spawn', 'sheet.langs': 'Languages', 'sheet.quest': 'Main quest',
      'stat.games': 'games & prototypes', 'stat.steam': 'Steam release', 'stat.ieee': 'IEEE VR 2026 works', 'stat.years': 'years making games',
      'qa.projects': 'My Projects', 'qa.projects.s': '{n} games & prototypes', 'qa.resume': 'Resume', 'qa.resume.s': 'Print or save as PDF', 'qa.skills': 'Skills', 'qa.skills.s': '{n} skills & tools', 'qa.contact': 'Contact', 'qa.contact.s': 'Let’s talk',
      'feat.steam': 'Now on Steam', 'feat.view': 'View on Steam', 'feat.details': 'Game page',

      'np.file': 'File', 'np.edit': 'Edit', 'np.view': 'View', 'np.help': 'Help', 'np.saveas': 'Save As…', 'np.print': 'Print…', 'np.exit': 'Exit', 'np.selectall': 'Select All', 'np.copy': 'Copy all',
      'np.zoomin': 'Zoom In', 'np.zoomout': 'Zoom Out', 'np.zoomreset': 'Default Zoom', 'np.about': 'About JoãoOS XP', 'np.status': 'Ln 1, Col 1',

      'mail.send': 'Send', 'mail.copy': 'Copy address', 'mail.vcard': 'Save contact (.vcf)', 'mail.vcard.ok': 'Contact card downloaded — open it to add João to your address book.', 'mail.to': 'To', 'mail.name': 'Your name', 'mail.from': 'Your email', 'mail.subject': 'Subject', 'mail.msg': 'Message',
      'mail.ph': 'Hi João, I saw your portfolio and…', 'mail.err': 'Please write a message first.', 'mail.opening': 'Opening your email app… if nothing happens, use “Copy address”.', 'mail.copied': 'Address copied: {e}',
      'mail.status': 'Messages open in your email app (nothing is stored)',
      'sub.job': 'Job opportunity', 'sub.collab': 'Collaboration', 'sub.jam': 'Game jam / project', 'sub.teach': 'Teaching / research', 'sub.hi': 'Just saying hi',
      'li.about': 'About', 'li.langs': 'Languages', 'li.skills': 'Key skills', 'li.open': 'Open full LinkedIn profile & posts',
      'cv.print': 'Print / Save as PDF', 'cv.hint': 'Tip: in the print dialog choose “Save as PDF”.', 'cv.status': 'The resume follows the site language',
      'cv.summary': 'Summary', 'cv.exp': 'Experience', 'cv.edu': 'Education', 'cv.research': 'Research & publications', 'cv.projects': 'Selected projects', 'cv.awards': 'Awards & recognition', 'cv.skills': 'Skills', 'cv.langs': 'Languages',
      'cv.dev': 'Engines & code', 'cv.design': 'Design', 'cv.xr': 'XR & immersive', 'cv.prod': 'Production & tools',
    },
    pt: {
      'meta.title': 'João Anisio — Programador e Designer de Jogos · Portfólio',
      'meta.desc': 'Portfólio de João Anisio Marinho da Nobrega — programador e designer de jogos (Godot, Unity), professor de Jogos Digitais na UFRN e líder de equipe XR no AKCIT. Criador de Malleus Maleficarum na Steam.',
      close: 'Fechar', start: 'iniciar',
      'boot.skip': 'clique para pular', 'login.begin': 'Para começar, clique no seu nome', 'login.sub': 'Programador e Designer de Jogos', 'login.off': 'Depois de entrar, explore a área de trabalho',
      'tray.lang': 'Idioma: clique para alternar (PT / EN)', 'tray.sound': 'Sons da interface', 'tray.desktop': 'Mostrar a área de trabalho',
      'sm.all': 'Todos os Programas', 'sm.programs': 'Programas', 'sm.places': 'Locais e links', 'sm.back': 'Voltar', 'sm.logoff': 'Fazer Logoff', 'sm.turnoff': 'Desligar',
      'ctx.open': 'Abrir', 'ctx.refresh': 'Atualizar', 'ctx.display': 'Propriedades de Exibição', 'ctx.projects': 'Meus Projetos', 'ctx.terminal': 'Terminal', 'ctx.about': 'Sobre o JoãoOS XP',
      'wm.min': 'Minimizar', 'wm.max': 'Maximizar', 'wm.restore': 'Restaurar', 'wm.close': 'Fechar',
      'bal.malleus.t': 'Malleus Maleficarum já está na Steam!', 'bal.malleus.x': 'Meu metroidvania programado solo já está no ar. Venha conferir.', 'bal.malleus.a': 'Ver o jogo',
      'bal.contact.t': 'Gostou do que viu?', 'bal.contact.x': 'Vamos conversar sobre jogos, pesquisa ou uma colaboração.', 'bal.contact.a': 'Dizer olá',
      'egg.t': 'Cheat ativado!', 'egg.x': '+30 vidas. Você encontrou o código Konami.',
      'sd.title': 'Obrigado pela visita!', 'sd.text': 'Agora é seguro sair do JoãoOS XP. Tenha um ótimo dia — e vamos construir algo juntos.', 'sd.restart': 'Reiniciar', 'sd.contact': 'Dizer olá',

      'wel.sub': 'Perfil e destaques', 'wel.explore': 'Explorar', 'wel.now': 'Atualmente',
      'sheet.class': 'Classe', 'sheet.level': 'Nível', 'sheet.xp': 'XP para o próximo nível: {n}%', 'sheet.guild': 'Guilda', 'sheet.weapons': 'Armas', 'sheet.spawn': 'Origem', 'sheet.langs': 'Idiomas', 'sheet.quest': 'Missão',
      'stat.games': 'jogos e protótipos', 'stat.steam': 'lançamento na Steam', 'stat.ieee': 'trabalhos na IEEE VR 2026', 'stat.years': 'anos fazendo jogos',
      'qa.projects': 'Meus Projetos', 'qa.projects.s': '{n} jogos e protótipos', 'qa.resume': 'Currículo', 'qa.resume.s': 'Imprimir ou salvar em PDF', 'qa.skills': 'Habilidades', 'qa.skills.s': '{n} habilidades e ferramentas', 'qa.contact': 'Contato', 'qa.contact.s': 'Vamos conversar',
      'feat.steam': 'Agora na Steam', 'feat.view': 'Ver na Steam', 'feat.details': 'Página do jogo',

      'np.file': 'Arquivo', 'np.edit': 'Editar', 'np.view': 'Exibir', 'np.help': 'Ajuda', 'np.saveas': 'Salvar como…', 'np.print': 'Imprimir…', 'np.exit': 'Sair', 'np.selectall': 'Selecionar tudo', 'np.copy': 'Copiar tudo',
      'np.zoomin': 'Aumentar', 'np.zoomout': 'Diminuir', 'np.zoomreset': 'Zoom padrão', 'np.about': 'Sobre o JoãoOS XP', 'np.status': 'Lin 1, Col 1',

      'mail.send': 'Enviar', 'mail.copy': 'Copiar endereço', 'mail.vcard': 'Salvar contato (.vcf)', 'mail.vcard.ok': 'Cartão de contato baixado — abra-o para adicionar o João à sua agenda.', 'mail.to': 'Para', 'mail.name': 'Seu nome', 'mail.from': 'Seu e-mail', 'mail.subject': 'Assunto', 'mail.msg': 'Mensagem',
      'mail.ph': 'Oi João, vi seu portfólio e…', 'mail.err': 'Escreva uma mensagem primeiro.', 'mail.opening': 'Abrindo seu app de e-mail… se nada acontecer, use “Copiar endereço”.', 'mail.copied': 'Endereço copiado: {e}',
      'mail.status': 'A mensagem abre no seu app de e-mail (nada é armazenado)',
      'sub.job': 'Oportunidade de trabalho', 'sub.collab': 'Colaboração', 'sub.jam': 'Game jam / projeto', 'sub.teach': 'Docência / pesquisa', 'sub.hi': 'Só dizendo oi',
      'li.about': 'Sobre', 'li.langs': 'Idiomas', 'li.skills': 'Principais habilidades', 'li.open': 'Abrir perfil completo e publicações no LinkedIn',
      'cv.print': 'Imprimir / Salvar PDF', 'cv.hint': 'Dica: na janela de impressão escolha “Salvar como PDF”.', 'cv.status': 'O currículo acompanha o idioma do site',
      'cv.summary': 'Resumo', 'cv.exp': 'Experiência', 'cv.edu': 'Formação', 'cv.research': 'Pesquisa e publicações', 'cv.projects': 'Projetos selecionados', 'cv.awards': 'Prêmios e reconhecimentos', 'cv.skills': 'Habilidades', 'cv.langs': 'Idiomas',
      'cv.dev': 'Engines e código', 'cv.design': 'Design', 'cv.xr': 'XR e imersivo', 'cv.prod': 'Produção e ferramentas',
    },
  };

  // ---------------------------------------------------------------- apps: portfolio / career / system
  Object.assign(JOS.strings.en, {
    'desk.shortcuts': 'Desktop shortcuts', 'taskbar.label': 'Taskbar', 'ex.back': 'Back', 'ex.fwd': 'Forward', 'ex.up': 'Up', 'ex.search': 'Search projects…', 'ex.view': 'View',
    'ex.view.thumbs': 'Thumbnails', 'ex.view.list': 'List', 'ex.view.details': 'Details',
    'ex.sort': 'Sort', 'ex.sort.featured': 'Featured', 'ex.sort.name': 'Name', 'ex.sort.engine': 'Engine', 'ex.sort.kind': 'Type',
    'ex.coll': 'Folders', 'ex.details': 'Details', 'ex.c.all': 'All projects', 'ex.c.featured': 'Featured', 'ex.c.xr': 'VR & Research', 'ex.c.music': 'Music',
    'ex.objects': '{n} objects', 'ex.none': 'No projects match your search.', 'ex.hint': 'Select a project to see its details.',
    'ex.open': 'Open', 'ex.play': 'Play on itch.io', 'ex.listen': 'Listen',
    'ex.col.name': 'Name', 'ex.col.engine': 'Engine', 'ex.col.type': 'Type', 'ex.col.tagline': 'Description',
    'ex.kind.game': 'Game', 'ex.kind.serious': 'Serious game', 'ex.kind.xr': 'VR / XR', 'ex.kind.music': 'Music',
    'ex.engine': 'Engine', 'ex.type': 'Type', 'ex.role': 'Role', 'ex.award': 'Award',
    'pv.prevImg': 'Previous image', 'pv.nextImg': 'Next image', 'pv.play': 'Play on itch.io', 'pv.steam': 'View on Steam', 'pv.copy': 'Copy link', 'pv.copied': 'Link copied!',
    'pv.prev': 'Previous', 'pv.next': 'Next', 'pv.shot': 'Screenshot {n}', 'pv.private': 'Not publicly available',
    'mal.team': 'Team', 'mal.dev': 'Developer', 'mal.status': 'Status', 'mal.released': 'Released on Steam', 'mal.more': 'Screenshots & project page',
    'sk.all': 'All', 'sk.dev': 'Engines & code', 'sk.design': 'Design', 'sk.xr': 'XR & immersive', 'sk.prod': 'Production & tools', 'sk.cat': 'Skill categories', 'sk.title': 'Skills',
    'sk.studying': 'Currently deepening my studies here', 'sk.used': 'Used in {n} projects', 'sk.show': 'Show {n} projects', 'sk.count': '{n} skills',
    'exp.all': 'All', 'exp.teach': 'Teaching', 'exp.research': 'Research', 'exp.games': 'Games', 'exp.it': 'IT', 'exp.now': 'Present', 'exp.filter': 'Filter by area',
    'exp.positions': 'positions', 'exp.since': 'since {y}', 'exp.positions.n': '{n} positions',
    'edu.academic': 'Education', 'edu.research': 'Research & Publications', 'edu.awards': 'See all achievements', 'edu.status': '{d} education entries · {p} publications',
    'ach.title': 'Achievements', 'ach.progress': '{a} of {b} unlocked', 'ach.view': 'View', 'ach.unlock': 'Unlock',
    'term.sub': 'Try “neofetch”', 'term.input': 'Command line',
    'dp.themes': 'Themes', 'dp.wall': 'Desktop', 'dp.set': 'Settings', 'dp.themes.h': 'Choose a color scheme for windows, taskbar and menus.',
    'dp.t.blue': 'Blue (default)', 'dp.t.olive': 'Olive Green', 'dp.t.silver': 'Silver',
    'dp.wall.h': 'Pick a wallpaper. “Automatic” follows the time of day on your device.', 'dp.w.auto': 'Automatic', 'dp.w.day': 'Day', 'dp.w.sunset': 'Sunset', 'dp.w.night': 'Night', 'dp.w.plain': 'Plain',
    'dp.lang': 'Language', 'dp.misc': 'Preferences', 'dp.sound': 'Play UI sounds', 'dp.motion': 'Reduce animations', 'dp.reset': 'Reset desktop & reload',
    'ab.icons': 'Icons', 'ab.fonts': 'Fonts', 'ab.version': 'Version', 'ab.licensed': 'This site is registered to', 'ab.built': 'Built with plain HTML, CSS and JavaScript — no frameworks and no third-party requests.',
    'ab.disc': 'Windows XP is a trademark of Microsoft Corporation. JoãoOS XP is an independent, fan-made tribute and is not affiliated with or endorsed by Microsoft.', 'ab.source': 'Source code',
  });
  Object.assign(JOS.strings.pt, {
    'desk.shortcuts': 'Atalhos da área de trabalho', 'taskbar.label': 'Barra de tarefas', 'ex.back': 'Voltar', 'ex.fwd': 'Avançar', 'ex.up': 'Acima', 'ex.search': 'Buscar projetos…', 'ex.view': 'Exibição',
    'ex.view.thumbs': 'Miniaturas', 'ex.view.list': 'Lista', 'ex.view.details': 'Detalhes',
    'ex.sort': 'Ordenar', 'ex.sort.featured': 'Destaques', 'ex.sort.name': 'Nome', 'ex.sort.engine': 'Engine', 'ex.sort.kind': 'Tipo',
    'ex.coll': 'Pastas', 'ex.details': 'Detalhes', 'ex.c.all': 'Todos os projetos', 'ex.c.featured': 'Destaques', 'ex.c.xr': 'VR e Pesquisa', 'ex.c.music': 'Música',
    'ex.objects': '{n} objetos', 'ex.none': 'Nenhum projeto corresponde à busca.', 'ex.hint': 'Selecione um projeto para ver os detalhes.',
    'ex.open': 'Abrir', 'ex.play': 'Jogar no itch.io', 'ex.listen': 'Ouvir',
    'ex.col.name': 'Nome', 'ex.col.engine': 'Engine', 'ex.col.type': 'Tipo', 'ex.col.tagline': 'Descrição',
    'ex.kind.game': 'Jogo', 'ex.kind.serious': 'Serious game', 'ex.kind.xr': 'VR / XR', 'ex.kind.music': 'Música',
    'ex.engine': 'Engine', 'ex.type': 'Tipo', 'ex.role': 'Função', 'ex.award': 'Prêmio',
    'pv.prevImg': 'Imagem anterior', 'pv.nextImg': 'Próxima imagem', 'pv.play': 'Jogar no itch.io', 'pv.steam': 'Ver na Steam', 'pv.copy': 'Copiar link', 'pv.copied': 'Link copiado!',
    'pv.prev': 'Anterior', 'pv.next': 'Próximo', 'pv.shot': 'Captura {n}', 'pv.private': 'Não disponível publicamente',
    'mal.team': 'Equipe', 'mal.dev': 'Desenvolvedor', 'mal.status': 'Status', 'mal.released': 'Lançado na Steam', 'mal.more': 'Capturas e página do projeto',
    'sk.all': 'Todas', 'sk.dev': 'Engines e código', 'sk.design': 'Design', 'sk.xr': 'XR e imersivo', 'sk.prod': 'Produção e ferramentas', 'sk.cat': 'Categorias de habilidades', 'sk.title': 'Habilidades',
    'sk.studying': 'Aprofundando meus estudos nesta área', 'sk.used': 'Usado em {n} projetos', 'sk.show': 'Mostrar {n} projetos', 'sk.count': '{n} habilidades',
    'exp.all': 'Todas', 'exp.teach': 'Docência', 'exp.research': 'Pesquisa', 'exp.games': 'Jogos', 'exp.it': 'TI', 'exp.now': 'Atual', 'exp.filter': 'Filtrar por área',
    'exp.positions': 'posições', 'exp.since': 'desde {y}', 'exp.positions.n': '{n} posições',
    'edu.academic': 'Formação', 'edu.research': 'Pesquisa e Publicações', 'edu.awards': 'Ver todas as conquistas', 'edu.status': '{d} formações · {p} publicações',
    'ach.title': 'Conquistas', 'ach.progress': '{a} de {b} desbloqueadas', 'ach.view': 'Ver', 'ach.unlock': 'Destravar',
    'term.sub': 'Experimente “neofetch”', 'term.input': 'Linha de comando',
    'dp.themes': 'Temas', 'dp.wall': 'Área de trabalho', 'dp.set': 'Configurações', 'dp.themes.h': 'Escolha um esquema de cores para janelas, barra de tarefas e menus.',
    'dp.t.blue': 'Azul (padrão)', 'dp.t.olive': 'Verde Oliva', 'dp.t.silver': 'Prata',
    'dp.wall.h': 'Escolha um papel de parede. “Automático” segue a hora do dia no seu dispositivo.', 'dp.w.auto': 'Automático', 'dp.w.day': 'Dia', 'dp.w.sunset': 'Pôr do sol', 'dp.w.night': 'Noite', 'dp.w.plain': 'Liso',
    'dp.lang': 'Idioma', 'dp.misc': 'Preferências', 'dp.sound': 'Tocar sons da interface', 'dp.motion': 'Reduzir animações', 'dp.reset': 'Restaurar área de trabalho e recarregar',
    'ab.icons': 'Ícones', 'ab.fonts': 'Fontes', 'ab.version': 'Versão', 'ab.licensed': 'Este site está registrado para', 'ab.built': 'Feito com HTML, CSS e JavaScript puros — sem frameworks e sem requisições de terceiros.',
    'ab.disc': 'Windows XP é marca registrada da Microsoft Corporation. O JoãoOS XP é uma homenagem independente feita por fã e não é afiliado nem endossado pela Microsoft.', 'ab.source': 'Código-fonte',
  });
})();
