// Builds the icon assets from tools/icons-src + tools/icons.config.mjs.
//   node tools/build-icons.mjs
// Outputs: assets/icons/silk.png, css/icons.css and the inline <symbol> sprite inside
// index.html (between the glyphs markers).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { silk, glyphs, brands, custom, keep } from './icons.config.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'tools/icons-src');
const OUT_PNG = path.join(ROOT, 'assets/icons/silk.png');
const OUT_CSS = path.join(ROOT, 'css/icons.css');
const INDEX = path.join(ROOT, 'index.html');
const cls = (n) => n.replace(/_/g, '-');

// ---------------------------------------------------------------- usage scan
// icons.config.mjs is the catalogue; only icons that the code references end up in the
// build (smaller sprite + smaller inline SVG). A reference is any quoted string equal to an
// icon name in js/*.js, or an i-/g- class/id in index.html and css/*.css.
const read = (f) => fs.readFileSync(path.join(ROOT, f), 'utf8');
const jsFiles = fs.readdirSync(path.join(ROOT, 'js')).filter((f) => f.endsWith('.js') && f !== 'media-manifest.js');
let corpus = jsFiles.map((f) => read('js/' + f)).join('\n');
corpus += '\n' + read('css/base.css') + '\n' + read('css/shell.css') + '\n' + read('css/apps.css');
const htmlRaw = fs.existsSync(INDEX) ? read('index.html') : '';
corpus += '\n' + htmlRaw.replace(/<!--glyphs:start-->[\s\S]*?<!--glyphs:end-->/, '');
const KEEP_ALL = process.argv.includes('--all');
const forced = new Set((keep || []).map(String));
const refd = (name, kind) => KEEP_ALL || forced.has(name) || (kind === 'silk'
  ? new RegExp(`['"]${name}['"]|\\bi-${cls(name)}\\b`).test(corpus)
  : new RegExp(`['"]${name}['"]|#g-${name}\\b|\\bg-${name}\\b`).test(corpus));


// Warn about literal icon names the code uses that are not in the catalogue (they would render empty).
{
  const found = (re) => [...corpus.matchAll(re)].map((m) => m[1]);
  const known = { silk: new Set([...silk, ...custom.map((c) => c.name)].map(cls)), glyph: new Set([...glyphs, ...Object.keys(brands)]) };
  const silkRefs = new Set([...found(/\bico\(\s*['"]([\w]+)['"]/g), ...found(/\bico:\s*['"]([\w]+)['"]/g)].map(cls));
  const glyphRefs = new Set([...found(/\bgl\(\s*['"]([\w-]+)['"]/g), ...found(/\b(?:glyph|brand):\s*['"]([\w-]+)['"]/g)]);
  const missing = [...[...silkRefs].filter((n) => !known.silk.has(n)).map((n) => 'sprite:' + n), ...[...glyphRefs].filter((n) => !known.glyph.has(n)).map((n) => 'glyph:' + n)];
  if (missing.length) console.warn('! icons used in the code but missing from tools/icons.config.mjs: ' + missing.join(', '));
  if (/\bico\(\s*[`]|\bgl\(\s*[`]/.test(corpus)) console.warn('! template-literal icon names found; add them to `keep` in tools/icons.config.mjs');
}

// ---------------------------------------------------------------- sprite (Silk + custom)
const cells = []; // { name, data }
for (const n of silk.filter((n) => refd(n, 'silk'))) {
  const file = path.join(SRC, 'silk', n + '.png');
  const { data, info } = await sharp(file).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  if (info.width !== 16 || info.height !== 16) throw new Error(`${n}.png is ${info.width}x${info.height}`);
  cells.push({ name: n, data });
}

// Hand-drawn icons from ASCII rows + palette.
for (const c of custom) {
  const data = Buffer.alloc(16 * 16 * 4);
  c.rows.forEach((row, y) => {
    if (row.length !== 16) throw new Error(`${c.name}: row ${y} has ${row.length} chars`);
    [...row].forEach((ch, x) => {
      if (ch === '.') return;
      const hex = c.palette[ch];
      if (!hex) throw new Error(`${c.name}: no palette entry for "${ch}"`);
      const i = (y * 16 + x) * 4;
      data[i] = parseInt(hex.slice(1, 3), 16); data[i + 1] = parseInt(hex.slice(3, 5), 16); data[i + 2] = parseInt(hex.slice(5, 7), 16); data[i + 3] = 255;
    });
  });
  if (c.rows.length !== 16) throw new Error(`${c.name}: needs 16 rows`);
  cells.push({ name: c.name, data });
}

const N = cells.length;
const sheet = Buffer.alloc(N * 16 * 16 * 4);
cells.forEach((c, i) => {
  for (let y = 0; y < 16; y++) c.data.copy(sheet, (y * N * 16 + i * 16) * 4, y * 16 * 4, (y + 1) * 16 * 4);
});
await sharp(sheet, { raw: { width: N * 16, height: 16, channels: 4 } })
  .png({ palette: true, colours: 256, dither: 0, effort: 10, compressionLevel: 9 })
  .toFile(OUT_PNG);

let css = `/* GENERATED by tools/build-icons.mjs — do not edit by hand.
   Colored 16x16 icons: Silk by Mark James (CC BY 2.5, famfamfam.com/lab/icons/silk). */
.ico{--s:1;--i:0;display:inline-block;flex:none;vertical-align:middle;width:calc(16px * var(--s));height:calc(16px * var(--s));background:url(../assets/icons/silk.png) no-repeat;background-size:calc(${N} * 16px * var(--s)) calc(16px * var(--s));background-position:calc(var(--i) * -16px * var(--s)) 0;image-rendering:pixelated;image-rendering:-moz-crisp-edges}
.ico-2{--s:2}.ico-3{--s:3}.ico-4{--s:4}
`;
cells.forEach((c, i) => { css += `.i-${cls(c.name)}{--i:${i}}\n`; });
fs.writeFileSync(OUT_CSS, css);

// ---------------------------------------------------------------- SVG glyph symbols
const symbols = [];
for (const n of glyphs.filter((n) => refd(n, 'glyph'))) {
  const svg = fs.readFileSync(path.join(SRC, 'pixelarticons', n + '.svg'), 'utf8');
  const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1].replace(/\s+/g, ' ').trim());
  if (!ds.length) throw new Error('no path in ' + n);
  symbols.push(`<symbol id="g-${n}" viewBox="0 0 24 24"><path d="${ds.join('')}"/></symbol>`);
}

// Brand marks: rasterise to 24x24, threshold, merge into rectangles.
function bitmapToPath(bits, W, H) {
  const used = new Uint8Array(W * H);
  let d = '';
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
    if (!bits[y * W + x] || used[y * W + x]) continue;
    let w = 1;
    while (x + w < W && bits[y * W + x + w] && !used[y * W + x + w]) w++;
    let h = 1;
    grow: while (y + h < H) {
      for (let i = 0; i < w; i++) if (!bits[(y + h) * W + x + i] || used[(y + h) * W + x + i]) break grow;
      h++;
    }
    for (let j = 0; j < h; j++) for (let i = 0; i < w; i++) used[(y + j) * W + x + i] = 1;
    d += `M${x} ${y}h${w}v${h}h-${w}z`;
  }
  return d;
}
for (const [id, slug] of Object.entries(brands).filter(([id]) => refd(id, 'glyph'))) {
  const svg = fs.readFileSync(path.join(SRC, 'brands', slug + '.svg'), 'utf8').replace('<svg', '<svg fill="#000"');
  const { data } = await sharp(Buffer.from(svg), { density: 72 * 8 })
    .resize(24, 24, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const bits = new Uint8Array(24 * 24);
  for (let i = 0; i < 24 * 24; i++) bits[i] = data[i * 4 + 3] >= 128 ? 1 : 0;
  symbols.push(`<symbol id="g-${id}" viewBox="0 0 24 24"><path d="${bitmapToPath(bits, 24, 24)}"/></symbol>`);
}

const sprite = `<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" style="position:absolute" aria-hidden="true" focusable="false">${symbols.join('')}</svg>`;

if (fs.existsSync(INDEX)) {
  const html = fs.readFileSync(INDEX, 'utf8');
  const re = /<!--glyphs:start-->[\s\S]*?<!--glyphs:end-->/;
  if (re.test(html)) {
    fs.writeFileSync(INDEX, html.replace(re, () => `<!--glyphs:start-->${sprite}<!--glyphs:end-->`));
    console.log('index.html: glyph sprite updated');
  } else console.warn('index.html has no <!--glyphs:start--> marker; sprite not injected');
}

const kb = (f) => (fs.statSync(f).size / 1024).toFixed(1) + ' KB';
console.log(`silk.png: ${N} icons, ${kb(OUT_PNG)} | icons.css ${kb(OUT_CSS)} | ${symbols.length} inline SVG symbols (${(sprite.length / 1024).toFixed(1)} KB)`);
